String valueDropClinica = "";
bool trocou = false;
bool updateClinica = true;
List<String> listaClinicas = [];
bool updatePaciente = true;
List<String> listaPacientes = [];
DateTime? dataInicial;
DateTime? dataFinal;
DateTime? dataAtendimento;
bool update = false;
int count = 0;
